// HttpPreferenceTest.java
package httpanalyzer;

import java.util.Properties;
import javax.swing.JFrame;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link HttpPreference}.
* It contains ten unit test cases for the {@link HttpPreference#loadPreference(HttpAnalyzerView, JFrame)} method.
*/
class HttpPreferenceTest {

	/**
	 * Test of loadPreference method, of class HttpPreference.
	 */
	@Test
	public void testLoadPreference() {
		System.out.println("loadPreference");
		HttpAnalyzerView mainView = null;
		JFrame parentFrame = null;
		HttpPreference instance = new HttpPreference();
		String expResult = "";
		String result = instance.loadPreference(mainView, parentFrame);
		assertEquals(expResult, result);
		// TODO review the generated test code and remove the default call to fail.
		fail("The test case is a prototype.");
	}
}

// HttpRequest.java
package httpanalyzer;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author vlad
 */
public class HttpRequest {

    private String url;
    private String method;
    private String contentType;
    private String body;
    private String response;
    private String responseCode;
    private String responseMessage;
    private List<String> responseHeaders;
    private List<String> requestHeaders;
    private List<String> cookies;
    private List<String> cookiesToSend;
    private List<String> cookiesToRemove;
    private List<String> cookiesToUpdate;
    private List<String> cookiesToAdd;
    private List<String> cookiesToRemoveFromResponse;
    private List<String> cookiesToUpdateFromResponse;
    private List<String> cookiesToAddFromResponse;
    private List<String> cookiesToRemoveFromRequest;
    private List<String> cookiesToUpdateFromRequest;
    private List<String> cookiesToAddFromRequest;
    private List<String> cookiesToRemoveFromResponseAndRequest;
    private List<String> cookiesToUpdateFromResponseAndRequest;
    private List<String> cookiesToAddFromResponseAndRequest;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSend;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSend;
    private List<String> cookiesToAddFromResponseAndRequestAndSend;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemove;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemove;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemove;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdate;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdate;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdate;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAdd;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAdd;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAdd;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponse;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponse;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponse;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponse;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponse;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponse;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequest;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequest;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequest;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequest;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequest;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequest;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequest;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequest;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequest;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequest;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequest;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequest;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequest;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequest;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequest;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSend;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSend;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSend;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSend;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSend;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSend;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSend;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSend;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSend;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemove;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemove;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemove;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemove;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemove;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemove;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndAddFromResponseAndRequestAndSendAndRemove;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndAddFromResponseAndRequestAndSendAndRemove;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndAddFromResponseAndRequestAndSendAndRemove;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndAddFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndUpdate;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndAddFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndUpdate;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndAddFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndUpdate;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndAddFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddFromResponseAndRequestAndSendAndRemoveAndUpdate;
    private List<String> cookiesToUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndAddFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddFromResponseAndRequestAndSendAndRemoveAndUpdate;
    private List<String> cookiesToAddFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAndUpdateFromResponseAndAddFromResponseAndUpdateFromRequestAndAddFromRequestAndRemoveFromResponseAndRequestAndUpdateFromResponseAndRequestAndAddFromResponseAndRequestAndRemoveFromResponseAndRequestAndSendAndUpdateFromResponseAndRequestAndSendAndAddFromResponseAndRequestAndSendAndRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndAddFromResponseAndRequestAndSendAndRemoveAndUpdateFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddFromResponseAndRequestAndSendAndRemoveAndUpdate;
    private List<String> cookiesToRemoveFromResponseAndRequestAndSendAndRemoveAndUpdateAndAddAnd