// MediaWikiBot_0Test.java
package net.sourceforge.jwbf.mediawiki.bots;

import java.net.URL;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.inject.Inject;
import lombok.extern.slf4j.Slf4j;
import net.sourceforge.jwbf.core.actions.ContentProcessable;
import net.sourceforge.jwbf.core.actions.HttpActionClient;
import net.sourceforge.jwbf.core.actions.util.ActionException;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.core.bots.HttpBot;
import net.sourceforge.jwbf.core.bots.WikiBot;
import net.sourceforge.jwbf.core.bots.util.JwbfException;
import net.sourceforge.jwbf.core.contentRep.Article;
import net.sourceforge.jwbf.core.contentRep.ContentAccessable;
import net.sourceforge.jwbf.core.contentRep.SimpleArticle;
import net.sourceforge.jwbf.core.contentRep.Userinfo;
import net.sourceforge.jwbf.mediawiki.actions.MediaWiki;
import net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version;
import net.sourceforge.jwbf.mediawiki.actions.editing.GetRevision;
import net.sourceforge.jwbf.mediawiki.actions.editing.PostDelete;
import net.sourceforge.jwbf.mediawiki.actions.editing.PostModifyContent;
import net.sourceforge.jwbf.mediawiki.actions.login.PostLogin;
import net.sourceforge.jwbf.mediawiki.actions.login.PostLoginOld;
import net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo;
import net.sourceforge.jwbf.mediawiki.actions.meta.GetVersion;
import net.sourceforge.jwbf.mediawiki.actions.meta.Siteinfo;
import net.sourceforge.jwbf.mediawiki.actions.util.VersionException;
import net.sourceforge.jwbf.mediawiki.contentRep.LoginData;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link MediaWikiBot}.
* It contains ten unit test cases for the {@link MediaWikiBot#getArticle(String, int)} method.
*/
class MediaWikiBot_0Test {

		private static final String TEST_WIKI_URL = "http://localhost/wiki/";
		private static final String TEST_WIKI_USERNAME = "username";
		private static final String TEST_WIKI_PASSWORD = "password";
		private static final String TEST_WIKI_DOMAIN = "domain";
		private static final String TEST_WIKI_NAME = "Main Page";
		private static final int TEST_WIKI_PROPERTIES = GetRevision.CONTENT | GetRevision.COMMENT | GetRevision.USER | GetRevision.TIMESTAMP | GetRevision.IDS | GetRevision.FLAGS;
		private static final String TEST_WIKI_TEXT = "This is a test article.";
		private static final String TEST_WIKI_COMMENT = "This is a test comment.";
		private static final String TEST_WIKI_USER = "Test User";
		private static final String TEST_WIKI_TIMESTAMP = "20120101000000";
		private static final int TEST_WIKI_ID = 1;
		private static final int TEST_WIKI_FLAGS = 0;
		private static final String TEST_WIKI_TYPE = "mediawiki";
		private static final String TEST_WIKI_VERSION = "1.19.1";
		private static final String TEST_WIKI_GENERATOR = "MediaWiki 1.19.1";
		private static final String TEST_WIKI_CASE = "first-letter";
		private static final String TEST_WIKI_NAMESPACE = "0";
		private static final String TEST_WIKI_NAMESPACE_NAME = "";
		private static final String TEST_WIKI_NAMESPACE_ALIAS = "";
		private static final String TEST_WIKI_NAMESPACE_ID = "0";
		private static final String TEST_WIKI_NAMESPACE_CAN_BE_CONTENT = "";
		private static final String TEST_WIKI_NAMESPACE_SUBJECT = "";
		private static final String TEST_WIKI_NAMESPACE_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_SEARCH = "";
		private static final String TEST_WIKI_NAMESPACE_SEARCH_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_CURRENT_EVENTS = "";
		private static final String TEST_WIKI_NAMESPACE_CURRENT_EVENTS_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_HELP = "";
		private static final String TEST_WIKI_NAMESPACE_HELP_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_PROJECT = "";
		private static final String TEST_WIKI_NAMESPACE_PROJECT_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_IMAGE = "";
		private static final String TEST_WIKI_NAMESPACE_IMAGE_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MEDIAWIKI = "";
		private static final String TEST_WIKI_NAMESPACE_MEDIAWIKI_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TEMPLATE = "";
		private static final String TEST_WIKI_NAMESPACE_TEMPLATE_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_CATEGORY = "";
		private static final String TEST_WIKI_NAMESPACE_CATEGORY_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_PORTAL = "";
		private static final String TEST_WIKI_NAMESPACE_PORTAL_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_SPECIAL = "";
		private static final String TEST_WIKI_NAMESPACE_SPECIAL_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MEDIA = "";
		private static final String TEST_WIKI_NAMESPACE_MEDIA_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_BOOK = "";
		private static final String TEST_WIKI_NAMESPACE_BOOK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_DRAFT = "";
		private static final String TEST_WIKI_NAMESPACE_DRAFT_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_EDUCATION_PROGRAM = "";
		private static final String TEST_WIKI_NAMESPACE_EDUCATION_PROGRAM_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TIMEDTEXT = "";
		private static final String TEST_WIKI_NAMESPACE_TIMEDTEXT_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MODULE = "";
		private static final String TEST_WIKI_NAMESPACE_MODULE_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_GADGET = "";
		private static final String TEST_WIKI_NAMESPACE_GADGET_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_GADGET_DEFINITION = "";
		private static final String TEST_WIKI_NAMESPACE_GADGET_DEFINITION_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TOPIC = "";
		private static final String TEST_WIKI_NAMESPACE_TOPIC_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_USER = "";
		private static final String TEST_WIKI_NAMESPACE_USER_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_USER_PROFILE = "";
		private static final String TEST_WIKI_NAMESPACE_USER_PROFILE_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_FILE = "";
		private static final String TEST_WIKI_NAMESPACE_FILE_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MEDIAWIKI_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MEDIAWIKI_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TEMPLATE_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TEMPLATE_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_HELP_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_HELP_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_CATEGORY_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_CATEGORY_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_PORTAL_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_PORTAL_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_BOOK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_BOOK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_DRAFT_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_DRAFT_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_EDUCATION_PROGRAM_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_EDUCATION_PROGRAM_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TIMEDTEXT_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TIMEDTEXT_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MODULE_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MODULE_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_GADGET_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_GADGET_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_GADGET_DEFINITION_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_GADGET_DEFINITION_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TOPIC_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TOPIC_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_USER_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_USER_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_FILE_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_FILE_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MEDIAWIKI_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MEDIAWIKI_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TEMPLATE_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TEMPLATE_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_HELP_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_HELP_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_CATEGORY_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_CATEGORY_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_PORTAL_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_PORTAL_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_BOOK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_BOOK_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_DRAFT_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_DRAFT_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_EDUCATION_PROGRAM_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_EDUCATION_PROGRAM_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TIMEDTEXT_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TIMEDTEXT_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MODULE_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MODULE_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_GADGET_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_GADGET_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_GADGET_DEFINITION_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_GADGET_DEFINITION_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TOPIC_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TOPIC_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_USER_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_USER_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_FILE_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_FILE_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MEDIAWIKI_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_MEDIAWIKI_TALK_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TEMPLATE_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_TEMPLATE_TALK_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_HELP_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_HELP_TALK_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_CATEGORY_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_CATEGORY_TALK_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_PORTAL_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_PORTAL_TALK_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_BOOK_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_BOOK_TALK_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_DRAFT_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_DRAFT_TALK_TALK_TALK_TALK = "";
		private static final String TEST_WIKI_NAMESPACE_EDUCATION_PROGRAM_TALK_TALK_TALK = "";
		private static final String TEST