// TemplateUserTitlesTest.java
package net.sourceforge.jwbf.mediawiki.actions.queries;

import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_09;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_10;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_11;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_12;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_13;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_14;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_15;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_16;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_17;
import java.util.ArrayList;
import java.util.Collection;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import lombok.extern.slf4j.Slf4j;
import net.sourceforge.jwbf.core.actions.Get;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.mediawiki.actions.MediaWiki;
import net.sourceforge.jwbf.mediawiki.actions.util.MWAction;
import net.sourceforge.jwbf.mediawiki.actions.util.SupportedBy;
import net.sourceforge.jwbf.mediawiki.actions.util.VersionException;
import net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link TemplateUserTitles}.
* It contains ten unit test cases for the {@link TemplateUserTitles#processAllReturningText(String)} method.
*/
class TemplateUserTitlesTest {

		private static final String TEMPLATE_NAME = "Template:Test";
		private static final String TEMPLATE_NAME_2 = "Template:Test2";
		private static final String TEMPLATE_NAME_3 = "Template:Test3";
		private static final String TEMPLATE_NAME_4 = "Template:Test4";
		private static final String TEMPLATE_NAME_5 = "Template:Test5";
		private static final String TEMPLATE_NAME_6 = "Template:Test6";
		private static final String TEMPLATE_NAME_7 = "Template:Test7";
		private static final String TEMPLATE_NAME_8 = "Template:Test8";
		private static final String TEMPLATE_NAME_9 = "Template:Test9";
		private static final String TEMPLATE_NAME_10 = "Template:Test10";
		private static final String TEMPLATE_NAME_11 = "Template:Test11";
		private static final String TEMPLATE_NAME_12 = "Template:Test12";
		private static final String TEMPLATE_NAME_13 = "Template:Test13";
		private static final String TEMPLATE_NAME_14 = "Template:Test14";
		private static final String TEMPLATE_NAME_15 = "Template:Test15";
		private static final String TEMPLATE_NAME_16 = "Template:Test16";
		private static final String TEMPLATE_NAME_17 = "Template:Test17";
		private static final String TEMPLATE_NAME_18 = "Template:Test18";
		private static final String TEMPLATE_NAME_19 = "Template:Test19";
		private static final String TEMPLATE_NAME_20 = "Template:Test20";
		private static final String TEMPLATE_NAME_21 = "Template:Test21";
		private static final String TEMPLATE_NAME_22 = "Template:Test22";
		private static final String TEMPLATE_NAME_23 = "Template:Test23";
		private static final String TEMPLATE_NAME_24 = "Template:Test24";
		private static final String TEMPLATE_NAME_25 = "Template:Test25";
		private static final String TEMPLATE_NAME_26 = "Template:Test26";
		private static final String TEMPLATE_NAME_27 = "Template:Test27";
		private static final String TEMPLATE_NAME_28 = "Template:Test28";
		private static final String TEMPLATE_NAME_29 = "Template:Test29";
		private static final String TEMPLATE_NAME_30 = "Template:Test30";
		private static final String TEMPLATE_NAME_31 = "Template:Test31";
		private static final String TEMPLATE_NAME_32 = "Template:Test32";
		private static final String TEMPLATE_NAME_33 = "Template:Test33";
		private static final String TEMPLATE_NAME_34 = "Template:Test34";
		private static final String TEMPLATE_NAME_35 = "Template:Test35";
		private static final String TEMPLATE_NAME_36 = "Template:Test36";
		private static final String TEMPLATE_NAME_37 = "Template:Test37";
		private static final String TEMPLATE_NAME_38 = "Template:Test38";
		private static final String TEMPLATE_NAME_39 = "Template:Test39";
		private static final String TEMPLATE_NAME_40 = "Template:Test40";
		private static final String TEMPLATE_NAME_41 = "Template:Test41";
		private static final String TEMPLATE_NAME_42 = "Template:Test42";
		private static final String TEMPLATE_NAME_43 = "Template:Test43";
		private static final String TEMPLATE_NAME_44 = "Template:Test44";
		private static final String TEMPLATE_NAME_45 = "Template:Test45";
		private static final String TEMPLATE_NAME_46 = "Template:Test46";
		private static final String TEMPLATE_NAME_47 = "Template:Test47";
		private static final String TEMPLATE_NAME_48 = "Template:Test48";
		private static final String TEMPLATE_NAME_49 = "Template:Test49";
		private static final String TEMPLATE_NAME_50 = "Template:Test50";
		private static final String TEMPLATE_NAME_51 = "Template:Test51";
		private static final String TEMPLATE_NAME_52 = "Template:Test52";
		private static final String TEMPLATE_NAME_53 = "Template:Test53";
		private static final String TEMPLATE_NAME_54 = "Template:Test54";
		private static final String TEMPLATE_NAME_55 = "Template:Test55";
		private static final String TEMPLATE_NAME_56 = "Template:Test56";
		private static final String TEMPLATE_NAME_57 = "Template:Test57";
		private static final String TEMPLATE_NAME_58 = "Template:Test58";
		private static final String TEMPLATE_NAME_59 = "Template:Test59";
		private static final String TEMPLATE_NAME_60 = "Template:Test60";
		private static final String TEMPLATE_NAME_61 = "Template:Test61";
		private static final String TEMPLATE_NAME_62 = "Template:Test62";
		private static final String TEMPLATE_NAME_63 = "Template:Test63";
		private static final String TEMPLATE_NAME_64 = "Template:Test64";
		private static final String TEMPLATE_NAME_65 = "Template:Test65";
		private static final String TEMPLATE_NAME_66 = "Template:Test66";
		private static final String TEMPLATE_NAME_67 = "Template:Test67";
		private static final String TEMPLATE_NAME_68 = "Template:Test68";
		private static final String TEMPLATE_NAME_69 = "Template:Test69";
		private static final String TEMPLATE_NAME_70 = "Template:Test70";
		private static final String TEMPLATE_NAME_71 = "Template:Test71";
		private static final String TEMPLATE_NAME_72 = "Template:Test72";
		private static final String TEMPLATE_NAME_73 = "Template:Test73";
		private static final String TEMPLATE_NAME_74 = "Template:Test74";
		private static final String TEMPLATE_NAME_75 = "Template:Test75";
		private static final String TEMPLATE_NAME_76 = "Template:Test76";
		private static final String TEMPLATE_NAME_77 = "Template:Test77";
		private static final String TEMPLATE_NAME_78 = "Template:Test78";
		private static final String TEMPLATE_NAME_79 = "Template:Test79";
		private static final String TEMPLATE_NAME_80 = "Template:Test80";
		private static final String TEMPLATE_NAME_81 = "Template:Test81";
		private static final String TEMPLATE_NAME_82 = "Template:Test82";
		private static final String TEMPLATE_NAME_83 = "Template:Test83";
		private static final String TEMPLATE_NAME_84 = "Template:Test84";
		private static final String TEMPLATE_NAME_85 = "Template:Test85";
		private static final String TEMPLATE_NAME_86 = "Template:Test86";
		private static final String TEMPLATE_NAME_87 = "Template:Test87";
		private static final String TEMPLATE_NAME_88 = "Template:Test88";
		private static final String TEMPLATE_NAME_89 = "Template:Test89";
		private static final String TEMPLATE_NAME_90 = "Template:Test90";
		private static final String TEMPLATE_NAME_91 = "Template:Test91";
