// MapPreviewTest.java
package common;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import org.apache.log4j.Logger;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link MapPreview}.
* It contains ten unit test cases for the {@link MapPreview#getMapPreview(int)} method.
*/
class MapPreviewTest {

		private static final Logger logger = Logger.getLogger(MapPreviewTest.class);
		
		private static final String MAP_FILE = "testmap";
		private static final String MAP_IMAGE_SET = "desert";
		private static final Point MAP_AREA = new Point(10, 10);
		private static final Vector<Vector<Integer>> MAP_TILES = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_OBJECTS = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_UNITS = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_BUILDINGS = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_AMOUNT = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER = new Vector<Vector<Integer>>();
		private static final Vector<Vector<Integer>> MAP_RESOURCES_REGEN_TIME_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INITIAL_COUNTER_MAX_INIT