// MainTest.java
package visu.handball.moves;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JToolBar;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import visu.handball.moves.actions.AboutAction;
import visu.handball.moves.actions.ChangeColorsAction;
import visu.handball.moves.actions.CloseAction;
import visu.handball.moves.actions.CreateMovePdfAction;
import visu.handball.moves.actions.DeleteEventAction;
import visu.handball.moves.actions.NewAction;
import visu.handball.moves.actions.NewMoveEventAction;
import visu.handball.moves.actions.NewPassEventAction;
import visu.handball.moves.actions.NewSequenceAction;
import visu.handball.moves.actions.OpenAction;
import visu.handball.moves.actions.PauseAnimationAction;
import visu.handball.moves.actions.PrintActualSequenzAction;
import visu.handball.moves.actions.PrintMoveAction;
import visu.handball.moves.actions.SaveAction;
import visu.handball.moves.actions.SetMoveNameAction;
import visu.handball.moves.actions.StartAnimationAction;
import visu.handball.moves.actions.StartOneSequenceAnimationAction;
import visu.handball.moves.actions.StopAnimationAction;
import visu.handball.moves.controller.CommentController;
import visu.handball.moves.controller.JMenuHelper;
import visu.handball.moves.controller.MouseController;
import visu.handball.moves.model.ColorModel;
import visu.handball.moves.model.HandballModel;
import visu.handball.moves.model.TableHandballModel;
import visu.handball.moves.model.TableSelectionListener;
import visu.handball.moves.resources.Resources;
import visu.handball.moves.views.CommentView;
import visu.handball.moves.views.EventTableCellDelayEditor;
import visu.handball.moves.views.EventTableCellRenderer;
import visu.handball.moves.views.Field;
import visu.handball.moves.views.PlayerToolBar;
import visu.handball.moves.views.StatusBar;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link Main}.
* It contains ten unit test cases for the {@link Main#getColorModel()} method.
*/
class MainTest {

	/**
	* Test case for {@link Main#getColorModel()} method.
	*/
	@Test
	void testGetColorModel() {
		// TODO: implement test
		fail("Not yet implemented");
	}
}

// MouseController.java
package visu.handball.moves.controller;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import visu.handball.moves.model.HandballModel;
import visu.handball.moves.model.Player;
import visu.handball.moves.model.PlayerEvent;
import visu.handball.moves.model.PlayerEvent.EventType;
import visu.handball.moves.model.PlayerEvent.PassType;
import visu.handball.moves.model.PlayerEvent.ShotType;
import visu.handball.moves.model.PlayerEvent.TackleType;
import visu.handball.moves.model.PlayerEvent.ThrowType;
import visu.handball.moves.model.PlayerEvent.TurnType;
import visu.handball.moves.model.PlayerEvent.WalkType;
import visu.handball.moves.views.Field;

/**
 * Controller für die Maus-Eingaben
 *
 * @author tommy
 */
public class MouseController implements MouseListener, MouseMotionListener {

    private Field field;
    private HandballModel model;
    private PlayerEvent event;
    private PlayerEvent.EventType eventType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.WalkType walkType;
    private PlayerEvent.PassType passType;
    private PlayerEvent.ShotType shotType;
    private PlayerEvent.TackleType tackleType;
    private PlayerEvent.ThrowType throwType;
    private PlayerEvent.TurnType turnType;
    private PlayerEvent.Walk