// MainTest.java
package visu.handball.moves;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JToolBar;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import visu.handball.moves.actions.AboutAction;
import visu.handball.moves.actions.ChangeColorsAction;
import visu.handball.moves.actions.CloseAction;
import visu.handball.moves.actions.CreateMovePdfAction;
import visu.handball.moves.actions.DeleteEventAction;
import visu.handball.moves.actions.NewAction;
import visu.handball.moves.actions.NewMoveEventAction;
import visu.handball.moves.actions.NewPassEventAction;
import visu.handball.moves.actions.NewSequenceAction;
import visu.handball.moves.actions.OpenAction;
import visu.handball.moves.actions.PauseAnimationAction;
import visu.handball.moves.actions.PrintActualSequenzAction;
import visu.handball.moves.actions.PrintMoveAction;
import visu.handball.moves.actions.SaveAction;
import visu.handball.moves.actions.SetMoveNameAction;
import visu.handball.moves.actions.StartAnimationAction;
import visu.handball.moves.actions.StartOneSequenceAnimationAction;
import visu.handball.moves.actions.StopAnimationAction;
import visu.handball.moves.controller.CommentController;
import visu.handball.moves.controller.JMenuHelper;
import visu.handball.moves.controller.MouseController;
import visu.handball.moves.model.ColorModel;
import visu.handball.moves.model.HandballModel;
import visu.handball.moves.model.TableHandballModel;
import visu.handball.moves.model.TableSelectionListener;
import visu.handball.moves.resources.Resources;
import visu.handball.moves.views.CommentView;
import visu.handball.moves.views.EventTableCellDelayEditor;
import visu.handball.moves.views.EventTableCellRenderer;
import visu.handball.moves.views.Field;
import visu.handball.moves.views.PlayerToolBar;
import visu.handball.moves.views.StatusBar;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link Main}.
* It contains ten unit test cases for the {@link Main#getCloseAction()} method.
*/
class MainTest {

	/**
	* Test case for {@link Main#getCloseAction()}.
	*/
	@Test
	void testGetCloseAction() {
		// TODO: Implement test case
	}
}

// MouseController.java
package visu.handball.moves.controller;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import visu.handball.moves.model.HandballModel;
import visu.handball.moves.model.Player;
import visu.handball.moves.model.PlayerEvent;
import visu.handball.moves.model.PlayerEvent.EventType;
import visu.handball.moves.model.PlayerEvent.PlayerPosition;
import visu.handball.moves.model.PlayerEvent.PlayerState;
import visu.handball.moves.model.PlayerEvent.PlayerTeam;
import visu.handball.moves.model.PlayerEvent.PlayerType;
import visu.handball.moves.model.Sequence;
import visu.handball.moves.views.Field;

/**
 * Controller f�r die Maus-Eingaben
 *
 * @author tommy
 */
public class MouseController implements MouseListener, MouseMotionListener {

    private HandballModel model;
    private Field field;
    private PlayerEvent playerEvent;
    private Player player;
    private Sequence sequence;
    private int x;
    private int y;
    private int x2;
    private int y2;
    private int x3;
    private int y3;
    private int x4;
    private int y4;
    private int x5;
    private int y5;
    private int x6;
    private int y6;
    private int x7;
    private int y7;
    private int x8;
    private int y8;
    private int x9;
    private int y9;
    private int x10;
    private int y10;
    private int x11;
    private int y11;
    private int x12;
    private int y12;
    private int x13;
    private int y13;
    private int x14;
    private int y14;
    private int x15;
    private int y15;
    private int x16;
    private int y16;
    private int x17;
    private int y17;
    private int x18;
    private int y18;
    private int x19;
    private int y19;
    private int x20;
    private int y20;
    private int x21;
    private int y21;
    private int x22;
    private int y22;
    private int x23;
    private int y23;
    private int x24;
    private int y24;
    private int x25;
    private int y25;
    private int x26;
    private int y26;
    private int x27;
    private int y27;
    private int x28;
    private int y28;
    private int x29;
    private int y29;
    private int x30;
    private int y30;
    private int x31;
    private int y31;
    private int x32;
    private int y32;
    private int x33;
    private int y33;
    private int x34;
    private int y34;
    private int x35;
    private int y35;
    private int x36;
    private int y36;
    private int x37;
    private int y37;
    private int x38;
    private int y38;
    private int x39;
    private int y39;
    private int x40;
    private int y40;
    private int x41;
    private int y41;
    private int x42;
    private int y42;
    private int x43;
    private int y43;
    private int x44;
    private int y44;
    private int x45;
    private int y45;
    private int x46;
    private int y46;
    private int x47;
    private int y47;
    private int x48;
    private int y48;
    private int x49;
    private int y49;
    private int x50;
    private int y50;
    private int x51;
    private int y51;
    private int x52;
    private int y52;
    private int x53;
    private int y53;
    private int x54;
    private int y54;
    private int x55;
    private int y55;
    private int x56;
    private int y56;
    private int x57;
    private int y57;
    private int x58;
    private int y58;
    private int x59;
    private int y59;
    private int x60;
    private int y60;
    private int x61;
    private int y61;
    private int x62;
    private int y62;
    private int x63;
    private int y63;
    private int x64;
    private int y64;
    private int x65;
    private int y65;
    private int x66;
    private int y66;
    private int x67;
    private int y67;
    private int x68;
    private int y68;
    private int x69;
    private int y69;
    private int x70;
    private int y70;
    private int x71;
    private int y71;
    private int x72;
    private int y72;
    private int x73;
    private int y73;
    private int x74;
    private int y74;
    private int x75;
    private int y75;
    private int x76;
    private int y76;
    private int x77;
    private int y77;
    private int x78;
    private int y78;
    private int x79;
    private int y79;
    private int x80;
    private int y80;
    private int x81;
    private int y81;
    private int x82;
    private int y82;
    private int x83;
    private int y83;
    private int x84;
    private int y84;
    private int x85;
    private int y85;
    private int x86;
    private int y86;
    private int x87;
    private int y87;
    private int x88;
    private int y88;
    private int x89;
    private int y89;
    private int x90;
    private int y90;
    private int x91;
    private int y91;
    private int x92;
    private int y92;
    private int x93;
    private int y93;
    private int x94;
    private int y94;
    private int x95;
    private int y95;
    private int x96;
    private int y96;
    private int x97;
    private int y97;
    private int x98;
    private int y98;
    private int x99;
    private int y99;
    private int x100;
    private int y100;
    private int x101;
    private int y101;
    private int x102;
    private int y102;
    private int x103;
    private int y103;
    private int x104;
    private int y104;
    private int x105;
    private int y105;
    private int x106;
    private int y106;
    private int x107;
    private int y107;
    private int x108;
    private int y108;
    private int x109;
    private int y109;
    private int x110;
    private int y110;
    private int x111;
    private int y111;
    private int x112;
    private int y112;
    private int x113;
    private int y113;
    private int x114;
    private int y114;
    private int x115;
    private int y115;
    private int x116;
    private int y116;
    private int x117;
    private int y117;
    private int x118;
    private int y118;
    private int x119;
    private int y119;
    private int x120;
    private int y120;
    private int x121;
    private int y121;
    private int x122;
    private int y122;
    private int x123;
    private int y123;
    private int x124;
    private int y124;
    private int x125;
    private int y125;
    private int x126;
    private int y126;
    private int x127;
    private int y127;
    private int x128;
    private int y128;
    private int x129;
    private int y129;
    private int x130;
    private int y130;
    private int x131;
    private int y131;
    private int x132;
    private int y132;
    private int x133;
    private int y133;
    private int x134;
    private int y134;
    private int x135;
    private int y135;
    private int x136;
    private int y136;
    private int x137;
    private int y137;
    private int x138;
    private int y138;
    private int x139;
    private int y139;
    private int x140;
    private int y140;
    private int x141;
    private int y141;
    private int x142;
    private int y142;
    private int x143;
    private int y143;
    private int x144;
    private int y144;
    private int x145;
    private int y145;
    private int x146;
    private int y146;
    private int x147;
    private int y147;
    private int x148;
    private int y148;
    private int x149;
    private int y149;
    private int x150;
    private int y150;
    private int x151;
    private int y151;
    private int x152;
    private int y152;
    private int x153;
    private int y153;
    private int x154;
    private int y154;
    private int x155;
    private int y155;
    private int x156;
    private int y156;
    private int x157;
    private int y157;
    private int x158;
    private int y158;
    private int x159;
    private int y159;
    private int x160;
    private int y160;
    private int x161;
    private int y161;
    private int x162;
    private int y162;
    private int x163;
    private int y163;
    private int x164;
    private int y164;
    private int x165;
    private int y165;
    private int x166;
    private int y166;
    private int x167;
    private int y167;
    private int x168;
    private int y168;
    private int x169;
    private int y169;
    private int x170;
    private int y170;
    private int x171;
    private int y171;
    private int x172;
    private int y172;
    private int x173;
    private int y173;
    private int x174;
    private int y174;
    private int x175;
    private int y175;
    private int x176;
    private int y176;
    private int x177;
    private int y177;
    private int x178;
    private int y178;
    private int x179;
    private int y179;
    private int x180;
    private int y180;
    private int x181;
    private int y181;
    private int x182;
    private int y182;
    private int x183;
    private int y183;
    private int x184;
    private int y184;
    private int x185;
    private int y185;
    private int x186;
    private int y186;
    private int x187;
    private int y187;
    private int x188;
    private int y188;
    private int x189;
    private int y189;
    private int x190;
    private int y190;
    private int x191;
    private int y191;
    private int x192;
    private int y192;
    private int x193;
    private int y193;
    private int x194;
    private int y194;
    private int x195;
    private int y195;
    private int x196;
    private int y196;
    private int x197;
    private int y197;
    private int x198;
    private int y198;
    private int x199;
    private int y199;
    private int x200;
    private int y200;
    private int x201;
    private int y201;
    private int x202;
    private int y202;
    private int x203;
    private int y203;
    private int x204;
    private int y204;
    private int x205;
    private int y205;
    private int x206;
    private int y206;
    private int x207;
    private int y207;
    private int x208;
    private int y208;
    private int x209;
    private int y209;
    private int x210;
    private int y210;
    private int x211;
    private int y211;
    private int x212;
    private int y212;
    private int x213;
    private int y213;
    private int x214;
    private int y214;
    private int x215;
    private int y215;
    private int x216;
    private int y216;
    private int x217;
    private int y217;
    private int x218;
    private int y218;
    private int x219;
    private int y219;
    private int x220;
    private int y220;
    private int x221;
    private int y221;
    private int x222;
    private int y222;
    private int x223;
    private int y223;
    private int x224;
    private int y224;
    private int x225;
    private int y225;
    private int x226;
    private int y226;
    private int x227;
    private int y227;
    private int x228;
    private int y228;
    private int x229;
    private int y229;
    private int x230;
    private int y230;
    private int x231;
    private int y231;
    private int x232;
    private int y232;
    private int x233;
    private int y233;
    private int x234;
    private int y234;
    private int x235;
    private int y235;
    private int x236;
    private int y236;
    private int x237;
    private int y237;
    private int x238;
    private int y238;
    private int x239;
    private int y239;
    private int x240;
    private int y240;
    private int x241;
    private int y241;
    private int x242;
    private int y242;
    private int x243;
    private int y243;
    private int x244;
    private int y244;
    private int x245;
    private int y245;
    private int x246;
    private int y246;
    private int x247;
    private int y247;
    private int x248;
    private int y248;
    private int x249;
    private int y249;
    private int x250;
    private int y250;
    private int x251;
    private int y251;
    private int x252;
    private int y252;
    private int x253;
    private int y253;
    private int x254;
    private int y254;
    private int x255;
    private int y255;
    private int x256;
    private int y256;
    private int x257;
    private int y257;
    private int x258;
    private int y258;
    private int x259;
    private int y259;
    private int x260;
    private int y260;
    private int x261