// ApplicationConfigurationTest.java
package fr.pingtimeout.jtail.configuration;

import fr.pingtimeout.jtail.gui.action.*;
import fr.pingtimeout.jtail.gui.controller.SelectIndexTypeListener;
import fr.pingtimeout.jtail.gui.model.JTailMainModel;
import fr.pingtimeout.jtail.gui.model.OpenFileModel;
import fr.pingtimeout.jtail.gui.view.JTailMainFrame;
import fr.pingtimeout.jtail.gui.view.OpenFileDialog;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import java.util.ResourceBundle;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ApplicationConfiguration}.
* It contains ten unit test cases for the {@link ApplicationConfiguration#chooseFileAction()} method.
*/
class ApplicationConfigurationTest {

	@Test
	void test_chooseFileAction_returns_a_new_ChooseFileAction_instance() {
		// Given
		ApplicationConfiguration applicationConfiguration = new ApplicationConfiguration();
		
		// When
		ChooseFileAction chooseFileAction = applicationConfiguration.chooseFileAction();
		
		// Then
		assertNotNull(chooseFileAction);
	}
	
	@Test
	void test_chooseFileAction_returns_a_new_ChooseFileAction_instance_each_time_it_is_called() {
		// Given
		ApplicationConfiguration applicationConfiguration = new ApplicationConfiguration();
		
		// When
		ChooseFileAction chooseFileAction1 = applicationConfiguration.chooseFileAction();
		ChooseFileAction chooseFileAction2 = applicationConfiguration.chooseFileAction();
		
		// Then
		assertNotSame(chooseFileAction1, chooseFileAction2);
	}
	
	@Test
	void test_chooseFileAction_returns_a_new_ChooseFileAction_instance_with_a_non_null_OpenFileModel() {
		// Given
		ApplicationConfiguration applicationConfiguration = new ApplicationConfiguration();
		
		// When
		ChooseFileAction chooseFileAction = applicationConfiguration.chooseFileAction();
		
		// Then
		assertNotNull(chooseFileAction.getOpenFileModel());
	}
	
	@Test
	void test_chooseFileAction_returns_a_new_ChooseFileAction_instance_with_a_non_null_OpenFileModel_each_time_it_is_called() {
		// Given
		ApplicationConfiguration applicationConfiguration = new ApplicationConfiguration();
		
		// When
		ChooseFileAction chooseFileAction1 = applicationConfiguration.chooseFileAction();
		ChooseFileAction chooseFileAction2 = applicationConfiguration.chooseFileAction();
		
		// Then
		assertNotSame(chooseFileAction1.getOpenFileModel(), chooseFileAction2.getOpenFileModel());
	}
	
	@Test
	void test_chooseFileAction_returns_a_new_ChooseFileAction_instance_with_a_non_null_OpenFileModel_each_time_it_is_called_and_the_OpenFileModel_is_a_singleton() {
		// Given
		ApplicationConfiguration applicationConfiguration = new ApplicationConfiguration();
		
		// When
		ChooseFileAction chooseFileAction1 = applicationConfiguration.chooseFileAction();
		ChooseFileAction chooseFileAction2 = applicationConfiguration.chooseFileAction();
		
		// Then
		assertSame(chooseFileAction1.getOpenFileModel(), chooseFileAction2.getOpenFileModel());
	}
	
	@Test
	void test_chooseFileAction_returns_a_new_ChooseFileAction_instance_with_a_non_null_OpenFileModel_each_time_it_is_called_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_singleton_and_the_OpenFileModel_is_a_sing