// A4j_3Test.java
package net.kencochrane.a4j;

import net.kencochrane.a4j.DAO.Cart;
import net.kencochrane.a4j.DAO.Product;
import net.kencochrane.a4j.DAO.Search;
import net.kencochrane.a4j.beans.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link A4j}.
* It contains ten unit test cases for the {@link A4j#ArtistSearch(String, String, String)} method.
*/
class A4j_3Test {

		private A4j a4j = new A4j();
		
		@Test
		void testArtistSearch_1() {
				ProductInfo productInfo = a4j.ArtistSearch("", "", "");
				assertNotNull(productInfo);
				assertNotNull(productInfo.getDetails());
				assertNotNull(productInfo.getDetails().getArtist());
				assertNotNull(productInfo.getDetails().getArtist().getArtistName());
				assertEquals("", productInfo.getDetails().getArtist().getArtistName());
				assertNotNull(productInfo.getDetails().getArtist().getArtistId());
				assertEquals("", productInfo.getDetails().getArtist().getArtistId());
				assertNotNull(productInfo.getDetails().getArtist().getArtistSortName());
				assertEquals("", productInfo.getDetails().getArtist().getArtistSortName());
				assertNotNull(productInfo.getDetails().getArtist().getArtistUrl());
				assertEquals("", productInfo.getDetails().getArtist().getArtistUrl());
				assertNotNull(productInfo.getDetails().getArtist().getArtistImageUrl());
				assertEquals("", productInfo.getDetails().getArtist().getArtistImageUrl());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiography());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiography());
				assertNotNull(productInfo.getDetails().getArtist().getArtistSimilarityUrl());
				assertEquals("", productInfo.getDetails().getArtist().getArtistSimilarityUrl());
				assertNotNull(productInfo.getDetails().getArtist().getArtistTracksUrl());
				assertEquals("", productInfo.getDetails().getArtist().getArtistTracksUrl());
				assertNotNull(productInfo.getDetails().getArtist().getArtistAlbumsUrl());
				assertEquals("", productInfo.getDetails().getArtist().getArtistAlbumsUrl());
				assertNotNull(productInfo.getDetails().getArtist().getArtistEditorialReview());
				assertEquals("", productInfo.getDetails().getArtist().getArtistEditorialReview());
				assertNotNull(productInfo.getDetails().getArtist().getArtistEditorialReviewSource());
				assertEquals("", productInfo.getDetails().getArtist().getArtistEditorialReviewSource());
				assertNotNull(productInfo.getDetails().getArtist().getArtistEditorialReviewContent());
				assertEquals("", productInfo.getDetails().getArtist().getArtistEditorialReviewContent());
				assertNotNull(productInfo.getDetails().getArtist().getArtistEditorialReviewUrl());
				assertEquals("", productInfo.getDetails().getArtist().getArtistEditorialReviewUrl());
				assertNotNull(productInfo.getDetails().getArtist().getArtistEditorialReviews());
				assertEquals(0, productInfo.getDetails().getArtist().getArtistEditorialReviews().size());
				assertNotNull(productInfo.getDetails().getArtist().getArtistSimilarArtists());
				assertEquals(0, productInfo.getDetails().getArtist().getArtistSimilarArtists().size());
				assertNotNull(productInfo.getDetails().getArtist().getArtistTopTracks());
				assertEquals(0, productInfo.getDetails().getArtist().getArtistTopTracks().size());
				assertNotNull(productInfo.getDetails().getArtist().getArtistTopAlbums());
				assertEquals(0, productInfo.getDetails().getArtist().getArtistTopAlbums().size());
				assertNotNull(productInfo.getDetails().getArtist().getArtistTopSongs());
				assertEquals(0, productInfo.getDetails().getArtist().getArtistTopSongs().size());
				assertNotNull(productInfo.getDetails().getArtist().getArtistTopSongsUrl());
				assertEquals("", productInfo.getDetails().getArtist().getArtistTopSongsUrl());
				assertNotNull(productInfo.getDetails().getArtist().getArtistTopAlbumsUrl());
				assertEquals("", productInfo.getDetails().getArtist().getArtistTopAlbumsUrl());
				assertNotNull(productInfo.getDetails().getArtist().getArtistTopTracksUrl());
				assertEquals("", productInfo.getDetails().getArtist().getArtistTopTracksUrl());
				assertNotNull(productInfo.getDetails().getArtist().getArtistSimilarArtistsUrl());
				assertEquals("", productInfo.getDetails().getArtist().getArtistSimilarArtistsUrl());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyUrl());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyUrl());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographySource());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographySource());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyContent());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyContent());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdated());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdated());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedDate());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedDate());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTime());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTime());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedYear());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedYear());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedMonth());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedMonth());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedDay());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedDay());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedHour());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedHour());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedMinute());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedMinute());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedSecond());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedSecond());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezone());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezone());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneAbbreviation());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneAbbreviation());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneOffset());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneOffset());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneDST());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneDST());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneRawOffset());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneRawOffset());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneDSTSavings());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneDSTSavings());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneId());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneId());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDisplayName());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDisplayName());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTOffset());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTOffset());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTStart());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTStart());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTEnd());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTEnd());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTStartMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTStartMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTEndMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTEndMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTOffsetMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTOffsetMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTSavingsMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTSavingsMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneRawOffsetMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneRawOffsetMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneIdMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneIdMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDisplayNameMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDisplayNameMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTOffsetMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTOffsetMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTStartMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTStartMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTEndMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTEndMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTSavingsMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTSavingsMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneRawOffsetMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneRawOffsetMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneIdMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneIdMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDisplayNameMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDisplayNameMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTOffsetMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTOffsetMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTStartMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTStartMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTEndMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTEndMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTSavingsMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTSavingsMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneRawOffsetMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneRawOffsetMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneIdMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneIdMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDisplayNameMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDisplayNameMillis());
				assertNotNull(productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTOffsetMillis());
				assertEquals("", productInfo.getDetails().getArtist().getArtistBiographyLastUpdatedTimezoneTimezoneDSTOffsetMillis());
			