// ObjectFactory_1Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ObjectFactory}.
* It contains ten unit test cases for the {@link ObjectFactory#createStaticPage()} method.
*/
class ObjectFactory_1Test {

	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_1() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(1);
		assertEquals(1, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_2() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(2);
		assertEquals(2, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_3() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(3);
		assertEquals(3, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_4() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(4);
		assertEquals(4, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_5() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(5);
		assertEquals(5, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_6() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(6);
		assertEquals(6, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_7() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(7);
		assertEquals(7, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_8() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(8);
		assertEquals(8, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_9() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(9);
		assertEquals(9, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_10() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(10);
		assertEquals(10, staticPage.getPageNumber());
	}
	
}

// ObjectFactory_2Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ObjectFactory}.
* It contains ten unit test cases for the {@link ObjectFactory#createStaticPage()} method.
*/
class ObjectFactory_2Test {
		
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_1() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(1);
		assertEquals(1, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_2() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(2);
		assertEquals(2, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_3() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(3);
		assertEquals(3, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_4() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(4);
		assertEquals(4, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_5() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(5);
		assertEquals(5, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_6() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(6);
		assertEquals(6, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_7() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(7);
		assertEquals(7, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_8() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(8);
		assertEquals(8, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_9() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(9);
		assertEquals(9, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_10() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(10);
		assertEquals(10, staticPage.getPageNumber());
	}
	
}

// ObjectFactory_3Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ObjectFactory}.
* It contains ten unit test cases for the {@link ObjectFactory#createStaticPage()} method.
*/
class ObjectFactory_3Test {
		
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_1() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(1);
		assertEquals(1, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_2() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(2);
		assertEquals(2, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_3() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(3);
		assertEquals(3, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_4() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(4);
		assertEquals(4, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_5() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(5);
		assertEquals(5, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_6() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(6);
		assertEquals(6, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_7() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(7);
		assertEquals(7, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_8() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(8);
		assertEquals(8, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_9() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(9);
		assertEquals(9, staticPage.getPageNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getPageNumber()} method.
	*/
	@Test
	void testCreateStaticPage_10() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setPageNumber(10);
		assertEquals(10, staticPage.getPageNumber());
	}
	
}

// ObjectFactory_4Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ObjectFactory}.
* It contains ten unit test cases for the {@link ObjectFactory#createStaticPage