// ObjectFactory_1Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ObjectFactory}.
* It contains ten unit test cases for the {@link ObjectFactory#createStaticPage()} method.
*/
class ObjectFactory_1Test {

	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getNumber()} method.
	*/
	@Test
	void testCreateStaticPage_1() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setNumber(1);
		assertEquals(1, staticPage.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getNumber()} method.
	*/
	@Test
	void testCreateStaticPage_2() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setNumber(2);
		assertEquals(2, staticPage.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getNumber()} method.
	*/
	@Test
	void testCreateStaticPage_3() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setNumber(3);
		assertEquals(3, staticPage.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getNumber()} method.
	*/
	@Test
	void testCreateStaticPage_4() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setNumber(4);
		assertEquals(4, staticPage.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getNumber()} method.
	*/
	@Test
	void testCreateStaticPage_5() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setNumber(5);
		assertEquals(5, staticPage.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getNumber()} method.
	*/
	@Test
	void testCreateStaticPage_6() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setNumber(6);
		assertEquals(6, staticPage.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getNumber()} method.
	*/
	@Test
	void testCreateStaticPage_7() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setNumber(7);
		assertEquals(7, staticPage.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getNumber()} method.
	*/
	@Test
	void testCreateStaticPage_8() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setNumber(8);
		assertEquals(8, staticPage.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getNumber()} method.
	*/
	@Test
	void testCreateStaticPage_9() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setNumber(9);
		assertEquals(9, staticPage.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	* It tests the {@link StaticPage#getNumber()} method.
	*/
	@Test
	void testCreateStaticPage_10() {
		StaticPage staticPage = new ObjectFactory().createStaticPage();
		staticPage.setNumber(10);
		assertEquals(10, staticPage.getNumber());
	}
	
}

// ObjectFactory_2Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ObjectFactory}.
* It contains ten unit test cases for the {@link ObjectFactory#createPage()} method.
*/
class ObjectFactory_2Test {
		
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	* It tests the {@link Page#getNumber()} method.
	*/
	@Test
	void testCreatePage_1() {
		Page page = new ObjectFactory().createPage();
		page.setNumber(1);
		assertEquals(1, page.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	* It tests the {@link Page#getNumber()} method.
	*/
	@Test
	void testCreatePage_2() {
		Page page = new ObjectFactory().createPage();
		page.setNumber(2);
		assertEquals(2, page.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	* It tests the {@link Page#getNumber()} method.
	*/
	@Test
	void testCreatePage_3() {
		Page page = new ObjectFactory().createPage();
		page.setNumber(3);
		assertEquals(3, page.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	* It tests the {@link Page#getNumber()} method.
	*/
	@Test
	void testCreatePage_4() {
		Page page = new ObjectFactory().createPage();
		page.setNumber(4);
		assertEquals(4, page.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	* It tests the {@link Page#getNumber()} method.
	*/
	@Test
	void testCreatePage_5() {
		Page page = new ObjectFactory().createPage();
		page.setNumber(5);
		assertEquals(5, page.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	* It tests the {@link Page#getNumber()} method.
	*/
	@Test
	void testCreatePage_6() {
		Page page = new ObjectFactory().createPage();
		page.setNumber(6);
		assertEquals(6, page.getNumber());
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	* It tests the {@link Page#getNumber()} method.
	*/
	@Test
	void testCreatePage_7() {
		Page page = new ObjectFactory().createPage();
		page.setNumber(7);
		assertEquals(7, page.getNumber());
	}
	
	/**
	*