// ObjectFactory_3Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ObjectFactory}.
* It contains ten unit test cases for the {@link ObjectFactory#createPages()} method.
*/
class ObjectFactory_3Test {

	/**
	* Test case for the {@link ObjectFactory#createPages()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePages_1() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pages result = fixture.createPages();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPages()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePages_2() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pages result = fixture.createPages();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPages()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePages_3() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pages result = fixture.createPages();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPages()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePages_4() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pages result = fixture.createPages();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPages()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePages_5() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pages result = fixture.createPages();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPages()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePages_6() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pages result = fixture.createPages();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPages()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePages_7() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pages result = fixture.createPages();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPages()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePages_8() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pages result = fixture.createPages();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPages()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePages_9() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pages result = fixture.createPages();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPages()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePages_10() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pages result = fixture.createPages();
		assertNotNull(result);
	}
	
}

// ObjectFactory_4Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ObjectFactory}.
* It contains ten unit test cases for the {@link ObjectFactory#createPagination()} method.
*/
class ObjectFactory_4Test {
		
	/**
	* Test case for the {@link ObjectFactory#createPagination()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePagination_1() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pagination result = fixture.createPagination();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPagination()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePagination_2() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pagination result = fixture.createPagination();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPagination()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePagination_3() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pagination result = fixture.createPagination();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPagination()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePagination_4() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pagination result = fixture.createPagination();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPagination()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePagination_5() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pagination result = fixture.createPagination();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPagination()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePagination_6() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pagination result = fixture.createPagination();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPagination()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePagination_7() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pagination result = fixture.createPagination();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPagination()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePagination_8() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pagination result = fixture.createPagination();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPagination()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePagination_9() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pagination result = fixture.createPagination();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPagination()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreatePagination_10() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		Pagination result = fixture.createPagination();
		assertNotNull(result);
	}
	
}

// ObjectFactory_5Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ObjectFactory}.
* It contains ten unit test cases for the {@link ObjectFactory#createStaticPage()} method.
*/
class ObjectFactory_5Test {
		
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreateStaticPage_1() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		StaticPage result = fixture.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreateStaticPage_2() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		StaticPage result = fixture.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreateStaticPage_3() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		StaticPage result = fixture.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreateStaticPage_4() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		StaticPage result = fixture.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreateStaticPage_5() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		StaticPage result = fixture.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreateStaticPage_6() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		StaticPage result = fixture.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreateStaticPage_7() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		StaticPage result = fixture.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreateStaticPage_8() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		StaticPage result = fixture.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreateStaticPage_9() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		StaticPage result = fixture.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*
	* @throws Exception
	* 				if any error occurs during the test.
	*/
	@Test
	void testCreateStaticPage_10() throws Exception {
		ObjectFactory fixture = new ObjectFactory();
		StaticPage result = fixture.createStaticPage();
		assertNotNull(result);
	}
	
}

// ObjectFactory_6Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ObjectFactory}.
* It contains ten unit test cases for the {@link ObjectFactory#createPage()} method.
*/
class ObjectFactory_6Test {
		
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	*
	* @throws Exception
	* 				if any error