// ObjectFactory_0Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ObjectFactory}.
* It contains ten unit test cases for the {@link ObjectFactory#createPage()} method.
*/
class ObjectFactory_0Test {

	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	*/
	@Test
	void testCreatePage_0() {
		ObjectFactory objectFactory = new ObjectFactory();
		Page result = objectFactory.createPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	*/
	@Test
	void testCreatePage_1() {
		ObjectFactory objectFactory = new ObjectFactory();
		Page result = objectFactory.createPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	*/
	@Test
	void testCreatePage_2() {
		ObjectFactory objectFactory = new ObjectFactory();
		Page result = objectFactory.createPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	*/
	@Test
	void testCreatePage_3() {
		ObjectFactory objectFactory = new ObjectFactory();
		Page result = objectFactory.createPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	*/
	@Test
	void testCreatePage_4() {
		ObjectFactory objectFactory = new ObjectFactory();
		Page result = objectFactory.createPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	*/
	@Test
	void testCreatePage_5() {
		ObjectFactory objectFactory = new ObjectFactory();
		Page result = objectFactory.createPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	*/
	@Test
	void testCreatePage_6() {
		ObjectFactory objectFactory = new ObjectFactory();
		Page result = objectFactory.createPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	*/
	@Test
	void testCreatePage_7() {
		ObjectFactory objectFactory = new ObjectFactory();
		Page result = objectFactory.createPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	*/
	@Test
	void testCreatePage_8() {
		ObjectFactory objectFactory = new ObjectFactory();
		Page result = objectFactory.createPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createPage()} method.
	*/
	@Test
	void testCreatePage_9() {
		ObjectFactory objectFactory = new ObjectFactory();
		Page result = objectFactory.createPage();
		assertNotNull(result);
	}
	
}

// ObjectFactory_1Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ObjectFactory}.
* It contains ten unit test cases for the {@link ObjectFactory#createStaticPage()} method.
*/
class ObjectFactory_1Test {
		
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*/
	@Test
	void testCreateStaticPage_0() {
		ObjectFactory objectFactory = new ObjectFactory();
		StaticPage result = objectFactory.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*/
	@Test
	void testCreateStaticPage_1() {
		ObjectFactory objectFactory = new ObjectFactory();
		StaticPage result = objectFactory.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*/
	@Test
	void testCreateStaticPage_2() {
		ObjectFactory objectFactory = new ObjectFactory();
		StaticPage result = objectFactory.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*/
	@Test
	void testCreateStaticPage_3() {
		ObjectFactory objectFactory = new ObjectFactory();
		StaticPage result = objectFactory.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*/
	@Test
	void testCreateStaticPage_4() {
		ObjectFactory objectFactory = new ObjectFactory();
		StaticPage result = objectFactory.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*/
	@Test
	void testCreateStaticPage_5() {
		ObjectFactory objectFactory = new ObjectFactory();
		StaticPage result = objectFactory.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*/
	@Test
	void testCreateStaticPage_6() {
		ObjectFactory objectFactory = new ObjectFactory();
		StaticPage result = objectFactory.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*/
	@Test
	void testCreateStaticPage_7() {
		ObjectFactory objectFactory = new ObjectFactory();
		StaticPage result = objectFactory.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*/
	@Test
	void testCreateStaticPage_8() {
		ObjectFactory objectFactory = new ObjectFactory();
		StaticPage result = objectFactory.createStaticPage();
		assertNotNull(result);
	}
	
	/**
	* Test case for the {@link ObjectFactory#createStaticPage()} method.
	*/
	@Test
	void testCreateStaticPage_9() {
		ObjectFactory objectFactory = new ObjectFactory();
		StaticPage result = objectFactory.createStaticPage();
		assertNotNull(result);
	}
	
}

// ObjectFactory_2Test.java
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.11 at 02:28:24 PM BST
//
package com.tripfilms.os.exttaglib.pagination.datatype;

import javax.xml.bind.annotation.XmlRegistry;
import org.